require('dotenv').config();
const mongoose = require('mongoose');
const Place = require('./models/Place');
const User  = require('./models/User');

const samplePlaces = [

  // ══════════ INDIA ══════════
  { name:'Ooty (Udhagamandalam)', description:'The Queen of Hill Stations nestled in the Nilgiri Mountains of Tamil Nadu. Famous for its lush tea gardens, Ooty Lake boat rides, botanical gardens with 650+ plant species, toy train through misty hills, and pleasant year-round cool climate.', location:'Ooty, Tamil Nadu, India', category:'hill', imageUrl:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', rating:4.5, budget:'low', bestTimeToVisit:'April – June, September – November', lat:11.4102, lng:76.6950 },
  { name:'Kodaikanal', description:'The Princess of Hill Stations in the Palani Hills of Tamil Nadu. Star-shaped Kodai Lake, Pillar Rocks, Coaker\'s Walk with misty valley views, and dense shola forests make it one of South India\'s most charming retreats.', location:'Kodaikanal, Tamil Nadu, India', category:'hill', imageUrl:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', rating:4.4, budget:'low', bestTimeToVisit:'April – June, September – October', lat:10.2381, lng:77.4892 },
  { name:'Munnar', description:'A breathtaking hill station in Kerala\'s Western Ghats, carpeted with endless stretches of tea plantations. Eravikulam National Park, Mattupetty Dam, and the rare Neelakurinji flowers (blooms once in 12 years) draw visitors year-round.', location:'Munnar, Kerala, India', category:'hill', imageUrl:'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80', rating:4.6, budget:'low', bestTimeToVisit:'September – March', lat:10.0889, lng:77.0595 },
  { name:'Taj Mahal', description:'A breathtaking ivory-white marble mausoleum on the banks of the Yamuna river. Built by Mughal emperor Shah Jahan, it is one of the Seven Wonders of the World and the greatest monument to love ever built.', location:'Agra, Uttar Pradesh, India', category:'historical', imageUrl:'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80', rating:4.9, budget:'low', bestTimeToVisit:'October – March', lat:27.1751, lng:78.0421 },
  { name:'Jaipur – Pink City', description:"Rajasthan's rose-pink capital — the magnificent Amber Fort, ornate Hawa Mahal, City Palace, and Jantar Mantar observatory. Vibrant bazaars overflow with gems, textiles, and spices.", location:'Jaipur, Rajasthan, India', category:'historical', imageUrl:'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80', rating:4.7, budget:'low', bestTimeToVisit:'October – March', lat:26.9124, lng:75.7873 },
  { name:'Varanasi (Kashi)', description:'One of the world\'s oldest living cities and Hinduism\'s holiest pilgrimage site on the Ganges. Ghats teeming with pilgrims, Ganga Aarti at dusk, ancient temples, and silk weaving create an overwhelming spiritual atmosphere.', location:'Varanasi, Uttar Pradesh, India', category:'historical', imageUrl:'https://images.unsplash.com/photo-1561361513-2d8ed8c83e8e?w=800&q=80', rating:4.6, budget:'low', bestTimeToVisit:'October – March', lat:25.3176, lng:82.9739 },
  { name:'Kerala Backwaters', description:"India's tropical paradise of lagoons, lakes, and canals fringed with coconut palms. Houseboat cruises through the backwaters of Alleppey (Alappuzha) are an unforgettable slow-travel experience.", location:'Alleppey, Kerala, India', category:'forest', imageUrl:'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80', rating:4.7, budget:'low', bestTimeToVisit:'September – March', lat:9.4981, lng:76.3388 },
  { name:'Leh-Ladakh', description:'A remote high-altitude desert plateau in northern India ringed by the Himalayas and Karakoram ranges. Ancient Buddhist monasteries, Pangong Lake, Nubra Valley sand dunes, and the world\'s highest motorable passes.', location:'Leh, Ladakh, India', category:'hill', imageUrl:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'June – September', lat:34.1526, lng:77.5770 },
  { name:'Goa Beaches', description:'India\'s party capital — golden beaches stretching along the Arabian Sea coast, Portuguese colonial architecture in Old Goa, spicy seafood, beach shacks, and a laid-back hippie vibe that is entirely its own.', location:'Goa, India', category:'beach', imageUrl:'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80', rating:4.6, budget:'low', bestTimeToVisit:'November – March', lat:15.2993, lng:74.1240 },
  { name:'Darjeeling', description:'The "Queen of the Himalayas" — terraced tea gardens producing the world\'s finest Darjeeling tea, sunrise views of Kanchenjunga from Tiger Hill, the heritage Toy Train, and the charming hill-town atmosphere.', location:'Darjeeling, West Bengal, India', category:'hill', imageUrl:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', rating:4.6, budget:'low', bestTimeToVisit:'March – May, October – November', lat:27.0410, lng:88.2663 },
  { name:'Manali', description:'Gateway to the Himalayan adventures — Rohtang Pass, Solang Valley, Hadimba Temple in cedar forests, and the Great Himalayan National Park. A favourite for skiing, paragliding, and trekking.', location:'Manali, Himachal Pradesh, India', category:'hill', imageUrl:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', rating:4.5, budget:'low', bestTimeToVisit:'October – June', lat:32.2396, lng:77.1887 },
  { name:'Rishikesh & Haridwar', description:'The yoga capital of the world on the banks of the Ganges in the Himalayan foothills. Laxman Jhula, white-water rafting, yoga ashrams, and the mesmerizing Ganga Aarti at Haridwar\'s Har Ki Pauri ghat.', location:'Rishikesh, Uttarakhand, India', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1561361513-2d8ed8c83e8e?w=800&q=80', rating:4.6, budget:'low', bestTimeToVisit:'September – November, February – May', lat:30.0869, lng:78.2676 },
  { name:'Andaman Islands', description:'A tropical paradise in the Bay of Bengal — pristine Radhanagar Beach (Asia\'s best), vibrant coral reefs at Elephant Beach, Cellular Jail heritage, and crystal-clear waters ideal for snorkelling and diving.', location:'Port Blair, Andaman Islands, India', category:'beach', imageUrl:'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&q=80', rating:4.7, budget:'medium', bestTimeToVisit:'October – May', lat:11.7401, lng:92.6586 },
  { name:'Mysuru (Mysore)', description:'The City of Palaces — the magnificent Mysore Palace illuminated by 100,000 bulbs on weekends, Chamundi Hill temple, sandalwood and silk bazaars, and the famous Dasara festival procession.', location:'Mysore, Karnataka, India', category:'historical', imageUrl:'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80', rating:4.6, budget:'low', bestTimeToVisit:'October – February', lat:12.2958, lng:76.6394 },
  { name:'Hampi', description:'A UNESCO World Heritage Site in Karnataka — the ruins of the mighty Vijayanagara Empire spread across a surreal boulder-strewn landscape. Virupaksha Temple, Vittala Temple\'s musical pillars, and ancient bazaars.', location:'Hampi, Karnataka, India', category:'historical', imageUrl:'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80', rating:4.7, budget:'low', bestTimeToVisit:'October – February', lat:15.3350, lng:76.4600 },
  { name:'Shimla', description:'The former summer capital of British India — Victorian architecture, the famous Mall Road, Jakhu Hill temple, toy train ride through apple orchards, and scenic Himalayan viewpoints.', location:'Shimla, Himachal Pradesh, India', category:'hill', imageUrl:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', rating:4.4, budget:'low', bestTimeToVisit:'March – June, December – January', lat:31.1048, lng:77.1734 },
  { name:'Spiti Valley', description:'A cold desert mountain valley in the Himalayas — one of the highest inhabited regions on Earth. Key Monastery, Chandratal Lake, ancient fossils, and stark lunar landscapes attract adventurous travellers.', location:'Spiti, Himachal Pradesh, India', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', rating:4.7, budget:'low', bestTimeToVisit:'June – September', lat:32.2451, lng:78.0338 },
  { name:'Valley of Flowers', description:'A UNESCO World Heritage Site in Uttarakhand — a remote high-altitude valley bursting with hundreds of species of wildflowers against a backdrop of Himalayan glaciers. Only accessible in summer.', location:'Chamoli, Uttarakhand, India', category:'hill', imageUrl:'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80', rating:4.8, budget:'low', bestTimeToVisit:'July – September', lat:30.7283, lng:79.6050 },
  { name:'Rann of Kutch', description:'The world\'s largest salt desert in Gujarat — a blindingly white expanse that transforms into a mirror under the full moon. The Rann Utsav festival brings tribal crafts, folk music, and camel rides.', location:'Kutch, Gujarat, India', category:'desert', imageUrl:'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80', rating:4.6, budget:'low', bestTimeToVisit:'November – February', lat:23.7337, lng:69.8597 },
  { name:'Coorg (Kodagu)', description:'Scotland of India — a misty coffee and spice plantation hill district in Karnataka. Abbey Falls, Nagarhole National Park, Dubare elephant camp, and the warrior Kodava culture make it unique.', location:'Coorg, Karnataka, India', category:'hill', imageUrl:'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80', rating:4.5, budget:'low', bestTimeToVisit:'October – March', lat:12.3375, lng:75.8069 },
  { name:'Jim Corbett National Park', description:"India's oldest national park in Uttarakhand — the best place to spot the Royal Bengal Tiger in its natural habitat. Elephant safaris, jeep safaris, and birdwatching in dense sal forests.", location:'Ramnagar, Uttarakhand, India', category:'forest', imageUrl:'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80', rating:4.6, budget:'medium', bestTimeToVisit:'November – June', lat:29.5300, lng:78.7747 },
  { name:'Udaipur – City of Lakes', description:'The most romantic city in India — palaces rising from azure lakes, the Lake Palace floating on Lake Pichola, Saheliyon-ki-Bari gardens, and spectacular sunsets from Sunset Point.', location:'Udaipur, Rajasthan, India', category:'historical', imageUrl:'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80', rating:4.7, budget:'medium', bestTimeToVisit:'October – March', lat:24.5854, lng:73.7125 },
  { name:'Chennai (Marina Beach)', description:"India's largest beach city — Marina Beach (world's second longest), Kapaleeshwarar Temple, Fort St. George, Mahabalipuram shore temples nearby, and the heartbeat of Carnatic music and Bharatanatyam.", location:'Chennai, Tamil Nadu, India', category:'city', imageUrl:'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80', rating:4.3, budget:'low', bestTimeToVisit:'November – February', lat:13.0827, lng:80.2707 },
  { name:'Kaziranga National Park', description:'A UNESCO World Heritage Site in Assam hosting two-thirds of the world\'s one-horned rhinoceroses. Also home to tigers, elephants, wild buffalo, and swamp deer in a floodplain landscape.', location:'Kaziranga, Assam, India', category:'forest', imageUrl:'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80', rating:4.7, budget:'medium', bestTimeToVisit:'November – April', lat:26.5775, lng:93.1711 },
  { name:'Mahabalipuram', description:'A UNESCO World Heritage Site on the Coromandel Coast — stunning 7th-century rock-cut shore temples, cave reliefs, and the massive Arjuna\'s Penance bas-relief carved from living rock.', location:'Mahabalipuram, Tamil Nadu, India', category:'historical', imageUrl:'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80', rating:4.5, budget:'low', bestTimeToVisit:'October – March', lat:12.6269, lng:80.1927 },
  { name:'Pondicherry (Puducherry)', description:'A slice of France on the Bay of Bengal — French Quarter with boulangeries and colonial villas, Sri Aurobindo Ashram, Auroville\'s meditation sphere, pristine beaches, and excellent French-Tamil cuisine.', location:'Pondicherry, India', category:'city', imageUrl:'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80', rating:4.5, budget:'low', bestTimeToVisit:'October – March', lat:11.9416, lng:79.8083 },

  // ══════════ SOUTHEAST ASIA ══════════
  { name:'Bali', description:'A magical island paradise known for its terraced rice paddies, ancient temples, vibrant arts scene, world-class surfing, and warm Balinese hospitality.', location:'Bali, Indonesia', category:'beach', imageUrl:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'April – October', lat:-8.3405, lng:115.0920 },
  { name:'Angkor Wat', description:'The largest religious monument in the world — a stunning 12th-century Khmer temple complex in the Cambodian jungle with intricate carvings and towering spires.', location:'Siem Reap, Cambodia', category:'historical', imageUrl:'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80', rating:4.9, budget:'low', bestTimeToVisit:'November – March', lat:13.4125, lng:103.8670 },
  { name:'Ha Long Bay', description:'A UNESCO World Heritage Site — thousands of limestone karst islands rising from emerald waters. Cruise through misty peaks, hidden sea caves, and floating fishing villages.', location:'Quảng Ninh, Vietnam', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80', rating:4.8, budget:'low', bestTimeToVisit:'October – April', lat:20.9101, lng:107.1839 },
  { name:'Phuket', description:"Thailand's largest island — Patong Beach, Phang Nga Bay sea caves, Big Buddha, Phi Phi day trips, excellent diving, and the vibrant Old Town with Sino-Portuguese architecture.", location:'Phuket, Thailand', category:'beach', imageUrl:'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800&q=80', rating:4.6, budget:'low', bestTimeToVisit:'November – April', lat:7.8804, lng:98.3923 },
  { name:'Tokyo', description:"Japan's futuristic capital blending ancient tradition with cutting-edge technology — from neon-lit Shibuya to serene Senso-ji Temple, world-class sushi, and neighbourhoods like no other city on Earth.", location:'Tokyo, Japan', category:'city', imageUrl:'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80', rating:4.8, budget:'high', bestTimeToVisit:'March – May, September – November', lat:35.6762, lng:139.6503 },
  { name:'Kyoto', description:"Japan's ancient imperial capital with 2,000+ religious sites including Kinkaku-ji, Fushimi Inari's thousand torii gates, Arashiyama bamboo grove, and the Gion geisha district.", location:'Kyoto, Japan', category:'historical', imageUrl:'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'March – May, October – November', lat:35.0116, lng:135.7681 },
  { name:'Komodo Island', description:"Home to the world's largest lizard — the fearsome Komodo dragon — plus world-class diving, pink sand beaches, and dramatic volcanic landscapes in eastern Indonesia.", location:'East Nusa Tenggara, Indonesia', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&q=80', rating:4.7, budget:'medium', bestTimeToVisit:'April – December', lat:-8.5469, lng:119.4824 },
  { name:'Luang Prabang', description:"Laos' most enchanting UNESCO World Heritage town — saffron-robed monks collecting alms at dawn, French colonial villas, the confluence of the Mekong and Nam Khan rivers.", location:'Luang Prabang, Laos', category:'city', imageUrl:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80', rating:4.7, budget:'low', bestTimeToVisit:'November – March', lat:19.8845, lng:102.1348 },
  { name:'Phi Phi Islands', description:'Thailand\'s most beautiful island group — turquoise lagoons, towering limestone cliffs, the famous Maya Bay, vibrant coral reefs, and postcard-perfect beaches.', location:'Krabi, Thailand', category:'beach', imageUrl:'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800&q=80', rating:4.7, budget:'low', bestTimeToVisit:'November – April', lat:7.7407, lng:98.7784 },
  { name:'Palawan', description:"The Philippines' last frontier — El Nido's limestone cliffs and lagoons, Coron's WWII shipwrecks, the UNESCO underground river, and pristine white-sand beaches.", location:'Palawan, Philippines', category:'beach', imageUrl:'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&q=80', rating:4.9, budget:'low', bestTimeToVisit:'November – May', lat:9.8349, lng:118.7384 },
  { name:'Sigiriya Rock Fortress', description:'A UNESCO World Heritage Site — a 200m rock fortress in Sri Lanka built by a 5th-century king, with remarkable frescoes, water gardens, and panoramic jungle views.', location:'Sigiriya, Sri Lanka', category:'historical', imageUrl:'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&q=80', rating:4.7, budget:'low', bestTimeToVisit:'December – April', lat:7.9570, lng:80.7603 },
  { name:'Zhangjiajie National Park', description:'The real-life inspiration for Avatar\'s floating mountains — thousands of towering sandstone pillars rising through the mist of Hunan province, China.', location:'Zhangjiajie, China', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1513415277900-a62401e19be4?w=800&q=80', rating:4.8, budget:'low', bestTimeToVisit:'April – October', lat:29.3252, lng:110.4345 },
  { name:'Bagan Temples', description:'Over 2,000 Buddhist temples and pagodas scattered across Myanmar\'s ancient plain. Hot air balloon rides at sunrise reveal a staggering panorama of spires stretching to the horizon.', location:'Bagan, Myanmar', category:'historical', imageUrl:'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80', rating:4.8, budget:'low', bestTimeToVisit:'November – February', lat:21.1717, lng:94.8585 },
  { name:'Mekong Delta', description:'Southern Vietnam\'s vast waterway network — floating markets, rice paddies, fruit orchards, and traditional villages offering authentic glimpses of rural Southeast Asian life.', location:'Mekong Delta, Vietnam', category:'forest', imageUrl:'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&q=80', rating:4.5, budget:'low', bestTimeToVisit:'December – April', lat:10.2417, lng:105.8009 },

  // ══════════ EAST ASIA ══════════
  { name:'Guilin & Li River', description:'Dramatic karst mountains mirrored in the Li River — one of China\'s most iconic landscapes, immortalized on the 20-yuan note and in centuries of classical art.', location:'Guilin, China', category:'hill', imageUrl:'https://images.unsplash.com/photo-1537531739086-f3e259a45b83?w=800&q=80', rating:4.7, budget:'low', bestTimeToVisit:'April – October', lat:25.2744, lng:110.2900 },
  { name:'Mount Fuji', description:"Japan's highest peak — a near-perfect volcanic cone that has inspired artists and pilgrims for centuries. The Fuji Five Lakes offer stunning reflections of the snow-capped summit.", location:'Shizuoka, Japan', category:'hill', imageUrl:'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'July – August', lat:35.3606, lng:138.7274 },
  { name:'Jeju Island', description:"South Korea's volcanic island — Hallasan crater, lava tube caves, tangerine orchards, dramatic coastline, and Seongsan Ilchulbong sunrise peak rising from the sea.", location:'Jeju, South Korea', category:'hill', imageUrl:'https://images.unsplash.com/photo-1570077181849-6bbc5a1e4f50?w=800&q=80', rating:4.6, budget:'medium', bestTimeToVisit:'April – June, September – November', lat:33.4890, lng:126.4983 },
  { name:'The Great Wall of China', description:'One of the greatest human construction feats — a 21,000 km fortification winding over mountains and through deserts. The Mutianyu and Badaling sections near Beijing are most accessible.', location:'Beijing, China', category:'historical', imageUrl:'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80', rating:4.8, budget:'low', bestTimeToVisit:'April – October', lat:40.4319, lng:116.5704 },

  // ══════════ SOUTH ASIA EXTRAS ══════════
  { name:'Maldives', description:'A necklace of 1,200 coral islands in the Indian Ocean — crystal lagoons, vibrant coral reefs, and luxurious overwater bungalows above turquoise water.', location:'Maldives, Indian Ocean', category:'beach', imageUrl:'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80', rating:4.9, budget:'high', bestTimeToVisit:'November – April', lat:3.2028, lng:73.2207 },
  { name:'Kathmandu Valley', description:'Nepal\'s ancient capital — Durbar Squares, Pashupatinath Temple on the Bagmati River, Boudhanath Stupa, and the gateway to Everest and Annapurna trekking.', location:'Kathmandu, Nepal', category:'historical', imageUrl:'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80', rating:4.7, budget:'low', bestTimeToVisit:'October – November, March – April', lat:27.7172, lng:85.3240 },
  { name:"Tiger's Nest – Bhutan", description:"The sacred Paro Taktsang Monastery clinging to a sheer 3,120m cliff face — Bhutan's most iconic site and one of Buddhism's holiest pilgrimage destinations.", location:'Paro, Bhutan', category:'hill', imageUrl:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', rating:4.9, budget:'high', bestTimeToVisit:'March – May, September – November', lat:27.4313, lng:89.4173 },

  // ══════════ MIDDLE EAST ══════════
  { name:'Petra', description:"Jordan's rose-red city half as old as time — the Nabataean city carved into cliff faces, featuring the iconic Treasury, Monastery, and a vast canyon landscape.", location:'Petra, Jordan', category:'historical', imageUrl:'https://images.unsplash.com/photo-1548786811-dd6e453ccca7?w=800&q=80', rating:4.9, budget:'medium', bestTimeToVisit:'March – May, September – November', lat:30.3285, lng:35.4444 },
  { name:'Cappadocia', description:'A surreal landscape of fairy chimneys, cave dwellings, and underground cities in central Turkey. Hot air balloon rides at dawn over honeycombed valleys are utterly magical.', location:'Cappadocia, Turkey', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1570939274717-7eda259b50ed?w=800&q=80', rating:4.9, budget:'medium', bestTimeToVisit:'April – June, September – November', lat:38.6431, lng:34.8289 },
  { name:'Dubai', description:"The city of superlatives — world's tallest building (Burj Khalifa), indoor ski slope, man-made Palm Island, gold souks, and a dazzling skyline rising from the desert.", location:'Dubai, UAE', category:'city', imageUrl:'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80', rating:4.7, budget:'high', bestTimeToVisit:'November – April', lat:25.2048, lng:55.2708 },
  { name:'Hagia Sophia', description:'A 6th-century Byzantine masterpiece in Istanbul — a colossal cathedral, later mosque, that showcases 1,500 years of architectural genius with its massive dome and golden mosaics.', location:'Istanbul, Turkey', category:'historical', imageUrl:'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'April – May, September – October', lat:41.0086, lng:28.9802 },
  { name:'Wadi Rum', description:"Jordan's Valley of the Moon — a protected desert wilderness of rose-red sandstone mountains and towering arches. Mars and Star Wars films were shot in this otherworldly landscape.", location:'Wadi Rum, Jordan', category:'desert', imageUrl:'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'March – May, September – November', lat:29.5722, lng:35.4197 },
  { name:'Samarkand', description:"The Silk Road's crown jewel — Uzbekistan's ancient city of turquoise domes and madrasas. The Registan Square is one of the most breathtaking architectural ensembles on Earth.", location:'Samarkand, Uzbekistan', category:'historical', imageUrl:'https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800&q=80', rating:4.8, budget:'low', bestTimeToVisit:'April – June, September – October', lat:39.6547, lng:66.9758 },

  // ══════════ EUROPE ══════════
  { name:'Santorini', description:'A stunning volcanic island in the Aegean Sea — iconic white-washed buildings with blue domed rooftops, dramatic cliffs, and breathtaking sunsets over the caldera.', location:'Santorini, Greece', category:'city', imageUrl:'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=80', rating:4.9, budget:'high', bestTimeToVisit:'June – September', lat:36.3932, lng:25.4615 },
  { name:'Eiffel Tower & Paris', description:"The City of Light — the Eiffel Tower, Louvre, Notre-Dame, Montmartre, world-class cuisine, and an atmosphere of art, romance, and fashion unrivalled anywhere on Earth.", location:'Paris, France', category:'city', imageUrl:'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=80', rating:4.8, budget:'high', bestTimeToVisit:'April – June, September – October', lat:48.8584, lng:2.2945 },
  { name:'Colosseum, Rome', description:'The mighty 2,000-year-old amphitheatre that once held 80,000 spectators for gladiatorial games — the most iconic symbol of the Roman Empire and ancient world.', location:'Rome, Italy', category:'historical', imageUrl:'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'April – June, September – October', lat:41.8902, lng:12.4922 },
  { name:'Swiss Alps', description:"Europe's most iconic mountain range — Matterhorn, Jungfrau, and Eiger towering above pristine glaciers and charming alpine villages. World-class skiing in winter, hiking in summer.", location:'Swiss Alps, Switzerland', category:'hill', imageUrl:'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&q=80', rating:4.9, budget:'high', bestTimeToVisit:'December – March, June – September', lat:46.8182, lng:8.2275 },
  { name:'Dubrovnik Old Town', description:"The Pearl of the Adriatic — a perfectly preserved medieval walled city on Croatia's Dalmatian coast. Walk the ancient walls for panoramic views of terracotta rooftops and sparkling sea.", location:'Dubrovnik, Croatia', category:'historical', imageUrl:'https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'May – June, September – October', lat:42.6507, lng:18.0944 },
  { name:'Northern Lights – Iceland', description:"Aurora borealis dancing across Iceland's vast dark skies. Add geysers, waterfalls, black sand beaches, and volcanic landscapes for one of Earth's most extraordinary destinations.", location:'Reykjavik, Iceland', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&q=80', rating:4.9, budget:'high', bestTimeToVisit:'September – March', lat:64.9631, lng:-19.0208 },
  { name:'Alhambra Palace', description:"Granada's Moorish masterpiece — a 14th-century palace of intricate Islamic geometry, reflecting pools, and gardens with panoramic views of the Sierra Nevada.", location:'Granada, Spain', category:'historical', imageUrl:'https://images.unsplash.com/photo-1558642891-54be180ea339?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'March – June, September – November', lat:37.1761, lng:-3.5881 },
  { name:'Neuschwanstein Castle', description:"The fairy-tale castle that inspired Disney's Sleeping Beauty — Ludwig II's fantastical 19th-century palace perched on a rugged Bavarian Alpine ridge above a stunning gorge.", location:'Bavaria, Germany', category:'historical', imageUrl:'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'May – September', lat:47.5576, lng:10.7498 },
  { name:'Prague Old Town', description:"One of Europe's best-preserved medieval cities — Charles Bridge, the astronomical clock chiming the hours, Gothic towers, and a riverside castle that glows gold at night.", location:'Prague, Czech Republic', category:'historical', imageUrl:'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'April – May, September – October', lat:50.0755, lng:14.4378 },
  { name:'Fjords of Norway', description:"Norway's deep glacial fjords — Geirangerfjord and Nærøyfjord are UNESCO Natural Wonders. Sheer 1,400m cliffs, thundering waterfalls, and mirror-like water.", location:'Western Norway', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', rating:4.9, budget:'high', bestTimeToVisit:'May – September', lat:61.4765, lng:6.8430 },
  { name:'Amalfi Coast', description:"A stunning 50-km stretch of cliffside villages, lemon groves, and turquoise sea along southern Italy's coast. Positano, Ravello, and Amalfi offer romance and extraordinary beauty.", location:'Amalfi Coast, Italy', category:'city', imageUrl:'https://images.unsplash.com/photo-1633321702518-8c3f7b42b750?w=800&q=80', rating:4.7, budget:'high', bestTimeToVisit:'May – October', lat:40.6340, lng:14.6027 },
  { name:'Cinque Terre', description:'Five colourful fishing villages clinging to sheer cliffs above the Ligurian Sea. The coastal hiking trail connecting Monterosso, Vernazza, Corniglia, Manarola, and Riomaggiore is world-famous.', location:'Liguria, Italy', category:'city', imageUrl:'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80', rating:4.7, budget:'medium', bestTimeToVisit:'April – June, September – October', lat:44.1461, lng:9.6439 },
  { name:'Plitvice Lakes', description:"Croatia's most spectacular national park — 16 turquoise lakes connected by waterfalls, surrounded by dense forest and limestone cliffs. A UNESCO World Heritage Site.", location:'Plitvice, Croatia', category:'forest', imageUrl:'https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80', rating:4.8, budget:'low', bestTimeToVisit:'April – June, September – October', lat:44.8654, lng:15.5820 },
  { name:'Sagrada Família', description:"Gaudí's unfinished Gothic masterpiece in Barcelona — a colossal basilica of mind-bending organic architecture and soaring towers under construction since 1882.", location:'Barcelona, Spain', category:'historical', imageUrl:'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'April – June, September – November', lat:41.4036, lng:2.1744 },
  { name:'Hallstatt', description:"Austria's most picturesque village on the edge of a dark alpine lake — a UNESCO World Heritage Site with a 7,000-year-old salt-mining heritage and fairy-tale mountain backdrop.", location:'Hallstatt, Austria', category:'hill', imageUrl:'https://images.unsplash.com/photo-1609342122563-a43ac8917a3a?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'May – September', lat:47.5622, lng:13.6493 },
  { name:'Venice', description:"La Serenissima — a city built on water with 400 bridges and 170 canals. Gondola rides, St Mark's Basilica, the Grand Canal, and Venetian masks make it utterly unique.", location:'Venice, Italy', category:'city', imageUrl:'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=800&q=80', rating:4.8, budget:'high', bestTimeToVisit:'April – June, September – October', lat:45.4408, lng:12.3155 },
  { name:'Amsterdam', description:'The Venice of the North — 17th-century canals, gabled merchant houses, the Van Gogh Museum, Rijksmuseum, cycling culture, and Keukenhof tulip gardens in spring.', location:'Amsterdam, Netherlands', category:'city', imageUrl:'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80', rating:4.7, budget:'medium', bestTimeToVisit:'April – May, September – October', lat:52.3676, lng:4.9041 },
  { name:'Scottish Highlands', description:"Vast wild landscapes of misty lochs, heather moorlands, ancient castles, and rugged mountains. The Isle of Skye, Loch Ness, and Glencoe are utterly dramatic.", location:'Scottish Highlands, UK', category:'hill', imageUrl:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', rating:4.7, budget:'medium', bestTimeToVisit:'May – September', lat:57.2897, lng:-4.4770 },
  { name:'Bruges', description:"Medieval Belgium's perfectly preserved city — a fairy-tale tangle of cobblestone lanes, canal boats, chocolate shops, craft beer cafes, and Gothic belfries frozen in the 15th century.", location:'Bruges, Belgium', category:'historical', imageUrl:'https://images.unsplash.com/photo-1491557345352-5929e343eb89?w=800&q=80', rating:4.7, budget:'medium', bestTimeToVisit:'April – October', lat:51.2093, lng:3.2247 },

  // ══════════ AFRICA ══════════
  { name:'Pyramids of Giza', description:'The last surviving wonder of the ancient world — three colossal pyramid tombs built 4,500 years ago, guarded by the Sphinx on the edge of the Sahara desert.', location:'Giza, Egypt', category:'historical', imageUrl:'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=800&q=80', rating:4.9, budget:'medium', bestTimeToVisit:'October – April', lat:29.9792, lng:31.1342 },
  { name:'Serengeti National Park', description:'The greatest wildlife spectacle on Earth — the annual Great Migration of 1.5 million wildebeest, 250,000 zebras, big cat predators, and vast golden plains.', location:'Tanzania, Africa', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80', rating:4.9, budget:'high', bestTimeToVisit:'June – October', lat:-2.3333, lng:34.8333 },
  { name:'Victoria Falls', description:"One of the Seven Natural Wonders — the world's largest waterfall by flow, where the Zambezi River plunges 108m into a gorge with a roar heard 40km away.", location:'Zimbabwe/Zambia, Africa', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80', rating:4.9, budget:'medium', bestTimeToVisit:'February – May', lat:-17.9243, lng:25.8572 },
  { name:'Sahara Desert', description:"The world's largest hot desert — camel treks across golden dunes, Berber camp nights under a million stars, and surreal landscapes that feel otherworldly.", location:'Merzouga, Morocco', category:'desert', imageUrl:'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80', rating:4.7, budget:'low', bestTimeToVisit:'October – April', lat:31.0998, lng:-4.0134 },
  { name:'Cape Town', description:"South Africa's Mother City — Table Mountain, penguins at Boulders Beach, Cape Point, the Cape Winelands, and vibrant waterfront culture.", location:'Cape Town, South Africa', category:'city', imageUrl:'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'November – March', lat:-33.9249, lng:18.4241 },
  { name:'Masai Mara', description:"Kenya's greatest wildlife reserve — year-round big cat sightings and the dramatic Great Migration Mara River crossings between July and October.", location:'Masai Mara, Kenya', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80', rating:4.8, budget:'high', bestTimeToVisit:'July – October', lat:-1.5021, lng:35.1436 },
  { name:'Zanzibar', description:"Tanzania's Spice Island — powdery white beaches, turquoise waters, the UNESCO Stone Town, rich Swahili culture, and spice plantation tours.", location:'Zanzibar, Tanzania', category:'beach', imageUrl:'https://images.unsplash.com/photo-1589299977027-90dbc2c2d74c?w=800&q=80', rating:4.7, budget:'medium', bestTimeToVisit:'June – October', lat:-6.1659, lng:39.2026 },
  { name:'Marrakech Medina', description:"Morocco's Red City — a labyrinthine medieval medina of souks, riads, and the chaotic Djemaa el-Fna square buzzing with entertainers, snake charmers, and street food.", location:'Marrakech, Morocco', category:'city', imageUrl:'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80', rating:4.6, budget:'low', bestTimeToVisit:'March – May, September – November', lat:31.6295, lng:-7.9811 },
  { name:'Chefchaouen', description:"Morocco's Blue Pearl — a mountain village painted entirely in shades of blue. The photogenic labyrinthine medina in the Rif Mountains feels like a dream.", location:'Chefchaouen, Morocco', category:'city', imageUrl:'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80', rating:4.7, budget:'low', bestTimeToVisit:'March – May, September – November', lat:35.1688, lng:-5.2636 },
  { name:'Sossusvlei Dunes', description:"Namibia's Namib Desert — the world's tallest orange-red sand dunes and the ghostly Dead Vlei with ancient camel-thorn trees standing in a white clay pan.", location:'Sossusvlei, Namibia', category:'desert', imageUrl:'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'May – October', lat:-24.7279, lng:15.3434 },
  { name:'Luxor Temples', description:"The world's greatest open-air museum — the Valley of the Kings, Karnak Temple, and Luxor Temple along the Nile, where pharaohs ruled for 1,500 years.", location:'Luxor, Egypt', category:'historical', imageUrl:'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'October – April', lat:25.6872, lng:32.6396 },
  { name:'Mount Kilimanjaro', description:"Africa's highest peak — a dormant volcano rising 5,895m from Tanzania's savannah plains. Multiple routes to the summit pass through five distinct climate zones.", location:'Kilimanjaro, Tanzania', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80', rating:4.8, budget:'high', bestTimeToVisit:'January – March, June – October', lat:-3.0674, lng:37.3556 },

  // ══════════ AMERICAS ══════════
  { name:'Machu Picchu', description:"The legendary Incan citadel in the Andes — one of the world's most spectacular archaeological sites, shrouded in cloud and mystery above the Sacred Valley.", location:'Cusco, Peru', category:'historical', imageUrl:'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&q=80', rating:4.9, budget:'medium', bestTimeToVisit:'May – September', lat:-13.1631, lng:-72.5450 },
  { name:'Amazon Rainforest', description:"The planet's lungs — a vast tropical ecosystem teeming with biodiversity. River cruises and jungle lodges offer encounters with pink dolphins, macaws, and anacondas.", location:'Manaus, Brazil', category:'forest', imageUrl:'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&q=80', rating:4.6, budget:'medium', bestTimeToVisit:'June – November', lat:-3.4653, lng:-62.2159 },
  { name:'Grand Canyon', description:"One of the world's most awe-inspiring natural wonders — a mile-deep gorge carved by the Colorado River over millions of years. Hiking, rafting, and helicopter tours.", location:'Arizona, USA', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=800&q=80', rating:4.9, budget:'medium', bestTimeToVisit:'March – May, September – November', lat:36.0544, lng:-112.1401 },
  { name:'New York City', description:"The city that never sleeps — Times Square, Central Park, the Statue of Liberty, world-class museums, Broadway shows, and the finest dining scene in North America.", location:'New York, USA', category:'city', imageUrl:'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80', rating:4.8, budget:'high', bestTimeToVisit:'April – June, September – November', lat:40.7128, lng:-74.0060 },
  { name:'Patagonia', description:'A vast wilderness at the tip of South America — Torres del Paine\'s granite towers, Perito Moreno glacier, untamed rivers, condors, and pumas in wild Patagonian steppes.', location:'Torres del Paine, Chile', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80', rating:4.8, budget:'high', bestTimeToVisit:'November – March', lat:-50.9423, lng:-73.4068 },
  { name:'Iguazu Falls', description:"The world's widest waterfall — 275 individual cascades straddling Argentina and Brazil, set in lush subtropical jungle that rings with the calls of exotic birds.", location:'Argentina/Brazil', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80', rating:4.9, budget:'medium', bestTimeToVisit:'March – May, August – October', lat:-25.6953, lng:-54.4367 },
  { name:'Galápagos Islands', description:'A living laboratory of evolution — volcanic islands where giant tortoises, marine iguanas, and blue-footed boobies allow remarkably close encounters.', location:'Galápagos, Ecuador', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&q=80', rating:4.9, budget:'high', bestTimeToVisit:'December – May', lat:-0.6500, lng:-90.4331 },
  { name:'Yellowstone National Park', description:"The world's first national park — a volcanic hotspot with 10,000+ geothermal features, Old Faithful geyser, rainbow hot springs, and abundant megafauna.", location:'Wyoming, USA', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1548786811-dd6e453ccca7?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'May – September', lat:44.4280, lng:-110.5885 },
  { name:'Yosemite Valley', description:"California's crown jewel — El Capitan, Half Dome, Yosemite Falls, giant sequoias, and flower-filled meadows in one of America's most iconic national parks.", location:'California, USA', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=800&q=80', rating:4.9, budget:'medium', bestTimeToVisit:'May – October', lat:37.7489, lng:-119.5885 },
  { name:'Rio de Janeiro', description:"Brazil's Marvellous City — Christ the Redeemer, Sugarloaf Mountain, Copacabana and Ipanema beaches, and the world's greatest carnival festival.", location:'Rio de Janeiro, Brazil', category:'city', imageUrl:'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80', rating:4.7, budget:'medium', bestTimeToVisit:'December – March', lat:-22.9068, lng:-43.1729 },
  { name:'Atacama Desert', description:"The driest non-polar desert on Earth — a lunar landscape of salt flats, geysers, flamingo lagoons, and some of the world's finest stargazing skies.", location:'Atacama, Chile', category:'desert', imageUrl:'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'March – May, September – November', lat:-22.9087, lng:-68.1997 },
  { name:'Havana', description:"Cuba's time-capsule capital — crumbling colonial grandeur, vintage American cars, salsa music from every doorway, and the warm infectious energy of Cuban people.", location:'Havana, Cuba', category:'city', imageUrl:'https://images.unsplash.com/photo-1570366583862-f91883984fde?w=800&q=80', rating:4.6, budget:'low', bestTimeToVisit:'December – April', lat:23.1136, lng:-82.3666 },
  { name:'Maui', description:"Hawaii's Valley Isle — the Road to Hana, Haleakalā volcano sunrise, world-class whale watching, snorkelling at Molokini Crater, and tropical waterfalls.", location:'Maui, Hawaii, USA', category:'beach', imageUrl:'https://images.unsplash.com/photo-1542259009477-d625272157b7?w=800&q=80', rating:4.8, budget:'high', bestTimeToVisit:'April – May, September – November', lat:20.7984, lng:-156.3319 },
  { name:'Banff & Lake Louise', description:'The jewel of the Canadian Rockies — emerald glacial lakes, soaring peaks, wildlife, hot springs, and world-class skiing. Lake Louise is one of the most photographed spots on Earth.', location:'Alberta, Canada', category:'hill', imageUrl:'https://images.unsplash.com/photo-1569880153113-76e33fc52d5f?w=800&q=80', rating:4.9, budget:'medium', bestTimeToVisit:'June – September', lat:51.4254, lng:-116.1773 },

  // ══════════ OCEANIA ══════════
  { name:'Great Barrier Reef', description:"The world's largest coral reef system off Queensland — home to 1,500+ fish species, sea turtles, manta rays, and humpback whales.", location:'Queensland, Australia', category:'beach', imageUrl:'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800&q=80', rating:4.7, budget:'high', bestTimeToVisit:'June – October', lat:-18.2871, lng:147.6992 },
  { name:'Fiordland & Milford Sound', description:"New Zealand's most dramatic scenery — sheer 1,200m cliffs, Stirling Falls, bottlenose dolphins, and fur seals in a fiord of absolute wilderness.", location:'Fiordland, New Zealand', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', rating:4.9, budget:'high', bestTimeToVisit:'December – March', lat:-45.3333, lng:167.5333 },
  { name:'Uluru (Ayers Rock)', description:"Australia's sacred sandstone monolith — a 550-million-year-old rock of deep spiritual significance to the Anangu people that glows fiery red at sunrise and sunset.", location:'Northern Territory, Australia', category:'desert', imageUrl:'https://images.unsplash.com/photo-1529108190281-9a4f620bc2d8?w=800&q=80', rating:4.8, budget:'medium', bestTimeToVisit:'April – June, August – October', lat:-25.3444, lng:131.0369 },
  { name:'Bora Bora', description:"French Polynesia's jewel — a volcanic peak ringed by a luminous turquoise lagoon. Overwater bungalows, vibrant coral gardens, and dramatic scenery make it the ultimate honeymoon paradise.", location:'Bora Bora, French Polynesia', category:'beach', imageUrl:'https://images.unsplash.com/photo-1559046376-e3c12c2f9d00?w=800&q=80', rating:4.9, budget:'high', bestTimeToVisit:'May – October', lat:-16.5004, lng:-151.7415 },
  { name:'Queenstown', description:"New Zealand's adventure capital — bungee jumping, skydiving, white-water rafting, skiing, and wine tasting against the stunning Remarkables mountain backdrop.", location:'Queenstown, New Zealand', category:'adventure', imageUrl:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', rating:4.8, budget:'high', bestTimeToVisit:'December – February, June – August', lat:-45.0312, lng:168.6626 },
  { name:'Sydney', description:"Australia's iconic harbour city — the Opera House, Harbour Bridge, Bondi Beach, vibrant neighbourhoods, and world-class food and wine culture.", location:'Sydney, Australia', category:'city', imageUrl:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', rating:4.8, budget:'high', bestTimeToVisit:'September – November, March – May', lat:-33.8568, lng:151.2153 },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅  Connected to MongoDB');

    await Place.deleteMany({});
    const inserted = await Place.insertMany(samplePlaces);
    console.log(`\n🌱  Seeded ${inserted.length} tourist places from around the world!\n`);

    // Stats by category
    const cats = {};
    const regions = {};
    inserted.forEach((p) => {
      cats[p.category] = (cats[p.category]||0)+1;
      const r = p.location.split(',').pop().trim();
      regions[r] = (regions[r]||0)+1;
    });

    console.log('📊  By category:');
    Object.entries(cats).sort((a,b)=>b[1]-a[1]).forEach(([k,v]) => console.log(`   ${k.padEnd(14)} ${v}`));

    // Admin user
    await User.deleteMany({ email: 'admin@tourist.com' });
    await User.create({ name: 'Admin User', email: 'admin@tourist.com', password: 'admin123', role: 'admin' });
    console.log('\n👤  Admin: admin@tourist.com / admin123');
  } catch (err) {
    console.error('❌  Seed error:', err.message);
  } finally {
    await mongoose.disconnect();
    console.log('🔌  Done!');
  }
}

seed();
